<?php
	define('MIGRATION_TBL', 'ecom_migrations_tbl');	
	define('USERS_TBL', 'ecom_users_tbl');
	define('ADMIN_SESSION_TBL', 'ecom_admin_session_tbl');
	define('PERMISSION_DATA_TBL', 'ecom_permissions_data_tbl');
	define('PERMISSION_TBL', 'ecom_users_permission_tbl');
	define('TAX_CLASSES_TBL', 'ecom_taxclass_tbl');
	define('BLOG_CATEGORY_TBL', 'ecom_blog_category_tbl');
	define('BLOG_TBL', 'ecom_blog_tbl');
	define('HOME_BANNER_TBL', 'ecom_home_banner_tbl');
	define('BRAND_TBL', 'ecom_brand_tbl');
	define('LEGAL_PAGE_TBL', 'ecom_legal_page_tbl');
	define('SEO_TBL', 'ecom_seo_content_tbl');
	define('OFFER_BANNER_TBL', 'ecom_offer_banner_tbl');
	define('TESTIMONIALS_TBL', 'ecom_testimonials_tbl');
	define('LOCATIONGROUP_TBL', 'ecom_locationcity_tbl');
	define('GROUP_TBL', 'ecom_locationgroup_tbl');
	define('LOCATION_TBL', 'ecom_location_tbl');
	define('PAGE_BANNER_TBL', 'ecom_page_banner_tbl');
	define('COMPANNY_INFO', 'ecom_contact_info_tbl');
	define('BRANCH_TBL', 'ecom_branch_tbl');
	define('COUPON_TBL', 'ecom_coupon_tbl');
	define('EMAIL_SETTINGS_TBL', 'ecom_email_settings_tbl');
	define('SMS_SETTINGS_TBL', 'ecom_sms_settings_tbl');
	define('PAYMENT_SETTINGS_TBL', 'ecom_payment_settings_tbl');
	define('SITE_SETTINGS_TBL', 'ecom_site_settings_tbl');
	define('ANALYTICS_TBL', 'ecom_analytics_tbl');
	define('CUSTOMER_TBL', 'ecom_customer_tbl');	
	define('STATE_TBL', 'ecom_state_tbl');
	define('CITY_TBL', 'ecom_city_tbl');	
	define('PINCODE_TBL', 'ecom_pincode_tbl');
	define('ATTRIBUTE_TBL', 'ecom_attribute_tbl');	
	define('ATTRIBUTE_GROUP_TBL', 'ecom_attribute_group_tbl');
	define('PRODUCT_ATTRIBUTES', 'ecom_product_attributes_tbl');
	define('PRODUCT_TBL', 'ecom_product_tbl');
	define('FORGOT_PASSWORD', 'ecom_forgot_password_tbl');	
	define('CONTACT_US_TBL', 'ecom_contact_us_tbl');
	define('SUBSCRIBE_TBL', 'ecom_subscribe_tbl');	
	define('CUSTOMER_ADDRESS_TBL', 'ecom_customer_address_tbl');
	define('CART_ITEM_TBL', 'ecom_cart_item_tbl');
	define('CART_TBL', 'ecom_cart_tbl');
	define('ORDER_ITEM_TBL', 'ecom_order_item_tbl');	
	define('ORDER_TBL', 'ecom_order_tbl');
	define('WISHLIST_TBL', 'ecom_wishlist_tbl');
	define('NOTIFICATION_EMAIL_TBL', 'ecom_notification_email_tbl');
	define('MEDIA_TBL', 'ecom_media_tbl');
	define('REVIEW_TBL', 'ecom_review_tbl');
	define('CONTRACTOR_TBL', 'ecom_contractor_tbl');
	define('CONTRACTOR_ENQUIRY_TBL', 'ecom_contractor_enquiry_tbl');
	define('CONTRACTOR_DETAILS_VIEWED_TBL', 'ecom_contractor_details_viwed');
	define('SERVICE_TAGS_TBL', 'ecom_service_tags_tbl');
	define('CONTRACTOR_PROJECT_TBL', 'ecom_contractor_project_tbl');
	define('CONTRACTOR_PROJECT_IMG_TBL', 'ecom_contractor_project_image_tbl');
	define('MAIN_CATEGORY_TBL', 'ecom_category_tbl');
	define('SUB_CATEGORY_TBL', 'ecom_sub_category_tbl');
	define('PRODUCT_VARIANTS', 'ecom_product_variants_tbl');
	define('RELATED_PRODUCTS', 'ecom_related_products_tbl');
	define('PRODUCT_VS_MAIN_CATEGORY', 'ecom_product_vs_main_category_tbl');
	define('PRODUCT_VS_SUB_CATEGORY', 'ecom_product_vs_sub_category_tbl');
	define('PRODUCT_OPTIONS', 'ecom_product_options_tbl');
	define('PRODUCT_OPTION_VARIANTS', 'ecom_product_option_variants_tbl');
	define('VENDOR_TBL', 'ecom_vendor_tbl');
	define('VENDOR_MAIN_CATEGORY_TBL', 'ecom_vendor_vs_main_category_tbl');
	define('VENDOR_SUB_CATEGORY_TBL', 'ecom_vendor_vs_sub_category_tbl');
	define('VENDOR_PRODUCTS_TBL', 'ecom_vendor_assigned_products_tbl');
	define('VENDOR_ORDER_TBL', ' ecom_vendor_order_tbl');
	define('VENDOR_ORDER_ITEM_TBL', 'ecom_vendor_order_item_tbl');
	define('VENDOR_PAYOUT_INVOICE_TBL', 'vendor_payout_invoice_tbl');
	define('VENDOR_PAYOUT_INVOICE_ITEM_TBL', 'vendor_payout_invoice_item_tbl');
	define('ORDER_RAZORPAY_PAYMENT_TBL', 'order_razorpay_payment_tbl');
	define('RETURN_REASON_TBL', 'ecom_return_reason_tbl');
	define('RETURN_SETTINGS_TBL', 'ecom_return_settings_tbl');
	define('CONTRACTOR_PROFILE_TBL', 'ecom_contractor_profile_tbl');
	define('VENDOR_PRODUCT_REQUEST_TBL', 'ecom_vendor_product_request_tbl');
	define('WORK_WITH_US_TBL','ecom_work_with_us_tbl');
	define('PRODUCT_REQUEST_STATUS_TBL','ecom_product_requset_status_tbl');
	define('ORDER_RESPONSE_STATUS_TBL','ecom_order_response_status_tbl');
	define('PAGINATION_TBL','ecom_pagination_tbl');
	define('PRODUCT_UNIT_TBL','ecom_product_unit_tbl');
	define('SPECIAL_BANNER_TBL', 'ecom_special_banner_tbl');
	define('PRODUCT_DISPLAY_TAG', 'ecom_display_tag_tbl');
	define('VENDOR_FORGOT_PASSWORD', 'ecom_vendor_forgot_password_tbl');
	define('VENDOR_RATTING_TBL', 'ecom_vendor_ratting_tbl');

	define('FILTER_GROUP_MASTER_TBL', 'ecom_filter_group_master_tbl');
	define('FILTER_MASTER_TBL', 'ecom_filter_master_tbl');
	define('FILTER_GROUP_VS_SUB_CATEGORY_TBL', 'ecom_filter_group_vs_subcategory_tbl');
	define('FILTER_VS_PRODUCT_TBL', 'ecom_filter_vs_product_tbl');


?>